name: entre_vizinhos_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_messaging: ^15.2.2
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.2


flutter:
  assets:
    - assets/banner-1.png
    - assets/banner-2.png
    - assets/banner-3.png
    - assets/icons/icon-google.png
    - assets/images/lancer-ralliart.png
    - assets/images/pc-gamer.png
    - assets/images/sofa.png
    - assets/icons/splash-icon.png

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
  - family: PlusJakartaSans
    fonts:
      - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
  uses-material-design: true

flutter_native_splash:
  color: "#23303b" # Cor de fundo do splash screen
  image: assets/icons/splash-icon.png # Caminho do logo da sua aplicação
  android_12:
    image: assets/icons/splash-icon.png
    color: "#23303b"
  android: true
  ios: true
